title: Noreen 
logo: /images/AWVI0695.JPG
#description: Discover my work in AI prompt engineering. Text, images, and code—all powered by state-of-the-art AI tools.
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true

