title: Noreen 
logo: /images/AWV
#description: Discover my work in AI prompt engineering. Text, images, and code—all powered by state-of-the-art AI tools.

show_downloads: true
theme: jekyll-theme-minimal
