title: Noreen
logo: /images/pro.jpg
# description: Discover my work in AI prompt engineering. Text, images, and code—all powered by state-of-the-art AI tools.
theme: jekyll-theme-minimal
custom_css: Assets/css/style.css

show_downloads: true


